version: "3"

services:
  web:
    build:
      context: ./web
    image: localhost:5000/youngstargram-web
    restart: always
    ports:
      - "80:80"
    links:
      - app:app

  app:
    build:
      context: ./api-server
    image: localhost:5000/youngstargram-api
    restart: always
    ports:
      - "3000:3000"
