version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile-dev
    ports:
      - "80:80"
    links:
      - app:app

  app:
    build:
      context: ./api-server
      dockerfile: Dockerfile-dev
    ports:
      - "4000:4000"
