version: "3"

services:
  web:
    build:
      context: ../packages/web
    ports:
      - "80:80"
      - "443:443"
    links:
      - app:app
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
  app:
    build:
      context: ../packages/api-server
    ports:
      - "4000:4000"
